### ISSUE TITLE
Badge printing throwing error

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/badge_printing#11]
When going to any of the badge printing page currently on live or test, getting the following 500 error:

```
Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 631, in respond
    self._do_respond(path_info)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 690, in _do_respond
    response.body = self.handler()
  File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 472, in with_timed
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 498, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 608, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 547, in with_rendering
    result = func(*args, **kwargs)
  File "/app/plugins/badge_printing/badge_printing/site_sections/kiosk_printing.py", line 62, in print_badges
    ribbon = attendee.ribbon_label if attendee.ribbon != c.NO_RIBBON \
  File "/app/plugins/uber/uber/models/__init__.py", line 347, in __getattr__
    suffixed = suffix_property.check(self, name)
  File "/app/plugins/uber/uber/decorators.py", line 139, in _suffix_property_check
    return prop_func(field_name, field_val)
  File "/app/plugins/uber/uber/models/__init__.py", line 331, in _label
    label = self.get_field(name).type.choices.get(val)
AttributeError: 'list' object has no attribute 'get'

```
This only appears to be affecting badges not flagged as minors.

**Comment by ianlayton** [comment]
May actually be related to the staff flag for a user. Was working on my instance and it was working until I put a staff flag on someone to print.

Update: upon further review, it appears to be affecting those flagged as dealers too. Had the same issue when I tried to flag someone as dealer.

**Comment by kitsuta** [comment]
The code needs to be updated to accommodate the change we made last year that supports multiple ribbons per attendee. Is this needed immediately to support pre-reg printing or anything?

**Comment by ianlayton** [comment]
Sooner then latter if possible. Not immediately but in the next day or two would be nice. Sorry for the OMG on it.

**Comment by jmdawson** [comment]
If badge printing will happen either this weekend (17-18 November) or the following (24-25 November), we'll need this fix applied soon so we can push a release in advance of it.
